import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-screen  h-screen relative flex flex-col justify-center items-center">
          <div className="flex shadow-md relative w-full max-sm:h-12 sm:h-[5vw]">
            <Image src={"/logo85.png"} alt="logo" fill objectFit="contain" />
          </div>
          <div className="bg-cyan-50  w-full h-[100%] flex justify-center items-center flex-col gap-[1vw]">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
